PracticalTask/PracticalTask/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('user.urls')),
    path('product/',include('product.urls')),
    path('admin/', admin.site.urls),
] +  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PracticalTask/product/urls.py
from django.urls import path
from .views import  *

app_name = 'product'

urlpatterns = [
    path('create/',ProductCreateView,name="create_product"),
    path('list/',ProductListView,name="list_product"),
    path('update/<int:pk>/',ProductUpdateView,name="update_product"),
    path('delete/<int:pk>/',ProductDeleteView,name="delete_product")
]

PracticalTask/user/urls.py
from django.urls import path
from .views import  *

urlpatterns = [
    path('login/',LoginView.as_view(),name='login'),
    path('verify_login/',LoginView.as_view(),name='verify_login'),
    path('admin_index/',AdminView.as_view(),name='admin_index'),
    path('home/<int:pk>',home,name='user_index'),
    path('create_user/',CreateUserView.as_view(),name='create_user'),
    path('activate_account/<uidb64>/<token>/',activate_account, name='activate_account'),
    path('list_user/',ListUserView,name='list_user'),
    path('delete_user/<int:pk>/',DeleteUserView,name='delete_user'),
    path('update_user/<int:pk>/',UpdateUserView,name='update_user')
]

PracticalTask/product/models.py
from django.db import models

# Create your models here.
class product(models.Model):
    name = models.CharField(max_length=50,blank=False)
    image = models.ImageField(upload_to='product_images/',blank=True)
    price = models.IntegerField(blank=False)
    create_date = models.DateTimeField(auto_now_add=True)
    last_update_date = models.DateTimeField(auto_now=True)

PracticalTask/product/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .serializer import ProductSerializer
from django.contrib import messages
from .models import product

# Create your views here.
def ProductCreateView(request):

    if request.method == "POST":
        try:
            name = request.POST.get('name')
            price = request.POST.get('price')
            image = request.FILES.get('image')  

            product_obj = product(name=name, price=price, image=image)
            product_obj.save()

            messages.info(request, 'Product Created Successfully!')
            return redirect('product:list_product')
        
        except Exception as e:
            messages.info(request, 'Something Went Wrong!')
            return redirect('product:create_product')
        
    return render(request, 'product/create_product.html')
        
def ProductListView(request):
    print(request.user)
    if request.method == "GET":
        products = product.objects.all()
        return render(request, 'product/list_product.html', {'products': products, 'user':request.user})
    
def ProductUpdateView(request, pk):
        
    product_obj = get_object_or_404(product,id=pk)
    if request.method == "POST":
        try:
            name = request.POST.get('name')
            price = request.POST.get('price')
            image = request.FILES.get('image')  
            product_obj.name = name
            product_obj.price = price
            
            if image:
                product_obj.image = image
            product_obj.save()

            messages.success(request, 'Product updated successfully!')
            return redirect('product:list_product')
        
        except Exception as e:
            messages.error(request, str(e))
            return redirect('product:list_product')
        
    return render(request, 'product/update_product.html', {'product': product_obj})

def ProductDeleteView(request, pk):
    product_obj = get_object_or_404(product,id=pk)

    print(request)

    if request.method == "POST":
        try:
            product_obj.delete()
            messages.success(request, 'Product Deleted successfully!')
            return redirect('product:list_product')
        except Exception as e:
            messages.error(request, str(e))
            return redirect('product:list_product')
        
    return redirect('product:list_product')
    

PracticalTask/product/templates/product/create_product.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Product</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    
</head>
<body>
    {% if messages %}
    <div class="message-container">
        {% for message in messages %}
            <div class="message-container {{ message.tags }}">
                <p>{{ message }}</p>
            </div>
        {% endfor %}
    </div>
    {% endif %}

    <div class="container">
    <h1>Create a New Product</h1>

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
    
        <label for="name">Product Name:</label>
        <input type="text" id="name" name="name" required><br>
        <br><br>
        <label for="price">Price:</label>
        <input type="number" id="price" name="price" step="0.01" required><br>
        <br><br>
        <label for="image">Product Image:</label>
        <input type="file" id="image" name="image"><br>
        <br><br>
        <button type="submit">Save Product</button>
    </form>

    <p><a href="{% url 'product:list_product' %}">Product List</a></p>
    </div>
</body>
</html>

PracticalTask/product/templates/product/list_product.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Product List</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    
</head>
<body>

    {% if messages %}
    <div class="message-container">
        {% for message in messages %}
            <div class="message-container {{ message.tags }}">
                <p>{{ message }}</p>
            </div>
        {% endfor %}
    </div>
    {% endif %}

    <div class="container">
    <h1>Product List</h1>

    {% if user.is_superuser %}
    <a href="{% url 'admin_index' %}" class="create-btn">Home Page</a>
    <a href="{% url 'product:create_product' %}" class="create-btn">Create New Product</a>
    {%endif%}

    <table class="product-table">
        <thead>
            <tr>
                <th>Product Name</th>
                <th>Price</th>
                <th>Image</th>
                {% if user.is_superuser %}
                    <th>Actions</th>
                {% endif %}
            </tr>
        </thead>
        <tbody>
            {% for product in products %}
                <tr>
                    <td>{{ product.name }}</td>
                    <td>{{ product.price }}</td>
                    <td>
                        {% if product.image %}
                            <img src="{{ product.image.url }}" alt="{{ product.name }}" width="100">
                        {% else %}
                            No Image
                        {% endif %}
                    </td>

                    {% if user.is_superuser %}
                        <td>
                            <a href="{% url 'product:update_product' product.id %}" class="edit-btn">Edit</a>

                            <form action="{% url 'product:delete_product' product.id %}" method="POST" style="display:inline;">
                                {% csrf_token %}
                                <button type="submit" class="delete-btn" onclick="return confirm('Are you sure you want to delete this product?')">Delete</button>
                            </form>
                            {% comment %} <a href="{% url 'product:delete_product' product.id %}" class="delete-btn" onclick="return confirm('Are you sure you want to delete this product?')">Delete</a> {% endcomment %}
                        </td>
                    {% endif %}
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
</body>
</html>

PracticalTask/product/templates/product/update_product.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Product</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    
</head>
<body>
    {% if messages %}
    <div class="message-container">
        {% for message in messages %}
            <div class="message-container {{ message.tags }}">
                <p>{{ message }}</p>
            </div>
        {% endfor %}
    </div>
    {% endif %}

    <div class="container">
    <h1>Update Product</h1>

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="name">Product Name:</label>
        <input type="text" id="name" name="name" value={{product.name}}><br>
        <br><br>
        <label for="price">Price:</label>
        <input type="number" id="price" name="price" step="0.01" value={{product.price}}><br>
        <br><br>
        <label for="image">Product Image:</label>
        {% if product.image %}
            <img src="{{ product.image.url }}" alt="{{ product.name }}" width="100">
        {% else %}
            <p>No image</p>
        {% endif %}
        <input type="file" id="image" name="image"><br>
        <br><br>
        <button type="submit">Save</button>
    </form>

    <p><a href="{% url 'product:list_product' %}">Product list</a></p>
    </div>
</body>
</html>