PracticalTask/PracticalTask/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('user.urls')),
    path('product/',include('product.urls')),
    path('admin/', admin.site.urls),
] +  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PracticalTask/product/urls.py
from django.urls import path
from .views import  *

app_name = 'product'

urlpatterns = [
    path('create/',ProductCreateView,name="create_product"),
    path('list/',ProductListView,name="list_product"),
    path('update/<int:pk>/',ProductUpdateView,name="update_product"),
    path('delete/<int:pk>/',ProductDeleteView,name="delete_product")
]

PracticalTask/user/urls.py
from django.urls import path
from .views import  *

urlpatterns = [
    path('login/',LoginView.as_view(),name='login'),
    path('verify_login/',LoginView.as_view(),name='verify_login'),
    path('admin_index/',AdminView.as_view(),name='admin_index'),
    path('home/<int:pk>',home,name='user_index'),
    path('create_user/',CreateUserView.as_view(),name='create_user'),
    path('activate_account/<uidb64>/<token>/',activate_account, name='activate_account'),
    path('list_user/',ListUserView,name='list_user'),
    path('delete_user/<int:pk>/',DeleteUserView,name='delete_user'),
    path('update_user/<int:pk>/',UpdateUserView,name='update_user')
]

PracticalTask/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    GENDER_CHOICES = [
        ('M', 'Male'),
        ('F', 'Female'),
        ('O', 'Other'),
        ('N', 'Not Specified'),
    ]

    gender = models.CharField(max_length=1, choices=GENDER_CHOICES,blank=True)
    phone_number = models.CharField(max_length=15, blank=True)
    address = models.TextField(blank=True) 

class UserProfile(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE, related_name='profile')
    image = models.ImageField(upload_to='profile_pics/', null=True, blank=True)
    create_date = models.DateTimeField(auto_now_add=True)
    last_update_date = models.DateTimeField(auto_now=True)

PracticalTask/user/views.py
from django.shortcuts import render, redirect, get_object_or_404
from rest_framework.views import APIView
from django.contrib.auth import authenticate
from rest_framework.authtoken.models import Token
from .serializers import CustomUserSerializer

from django.contrib.auth.tokens import default_token_generator
from django.shortcuts import render, redirect
from django.contrib import messages
from django.utils.http import urlsafe_base64_decode
from .handler_methods import send_activation_email
from django.contrib.auth import get_user_model
from django.utils.encoding import force_str
from .models import CustomUser

def activate_account(request, uidb64, token):
    try:

        uid = force_str(urlsafe_base64_decode(uidb64).decode())
        user = CustomUser.objects.get(pk=uid)
        print(uid,user)
        
        if default_token_generator.check_token(user, token):
           
            if request.method == 'POST':

                password = request.POST.get('password')
                confirm_password = request.POST.get('confirm_password')
                
                if password != confirm_password:
                    messages.error(request, "Passwords do not match.")
                    return render(request, 'user/failure.html')

                user.set_password(password)
                user.is_active = True
                user.save()

                return redirect('login')
        
            return render(request, 'user/set_password.html')

        else:
            messages.error(request, 'Invalid activation link or token has expired.')
            return render(request, 'user/failure.html')

    except Exception as e:
        print(e)
        messages.error(request, 'Invalid activation link.')
        return render(request, 'user/failure.html') 

def home(request, pk=None):
    user = get_object_or_404(CustomUser,id=pk)
    print("Home ",user.id)
    return render(request, 'user/index.html', {'user_id':user.id})

def ListUserView(request):
    if request.method == "GET":
        users = CustomUser.objects.all()
        print(users)
        return render(request, 'user/list_user.html', {"users":users})

def UpdateUserView(request,pk):
    print("login user :",request.user)
    user = get_object_or_404(CustomUser,id=pk)
    if request.method == "POST":
        try:
            serializer = CustomUserSerializer(user, data=request.POST, partial=True)
            if serializer.is_valid():
                serializer.save()
                messages.success(request, 'User updated successfully!')
                if request.user.is_superuser:
                    return redirect('list_user')
                else:
                    return render(request, 'user/index.html', {'user_id':user.id})
            
            messages.error(request, 'Something Went Wrong!')
            if request.user.is_superuser:
                    return redirect('list_user')
            else:
                return render(request, 'user/index.html', {'user_id':user.id})
        
        except Exception as e:
            messages.error(request, str(e))
            return redirect('list_user')
        
    return render(request, 'user/update_user.html', {"user":user, "login_user":request.user})

def DeleteUserView(request, pk):
    user = get_object_or_404(CustomUser,id=pk)

    if request.method == "POST":
        try:
            user.delete()
            messages.success(request, 'User Deleted successfully!')
            return redirect('list_user')
        except Exception as e:
            messages.error(request, str(e))
            return redirect('list_user')
        
    return redirect('list_user')

class AdminView(APIView):
    def get(self,request):
        return render(request,'user/admin_index.html')
  
class CreateUserView(APIView):
    def get(self, request):
        return render(request, 'user/create_user.html')
    
    def post(self, request):
        # print(request.data)
        serializer = CustomUserSerializer(data=request.data)
       
        if serializer.is_valid():
            user = serializer.save()  

            print("user:",user.pk)
            send_activation_email(user)
            messages.info(request, 'User Created Successfully!')
            return redirect('list_user')
        else:
            messages.error(request,str(serializer.error))
            return render(request, 'user/failure.html')

class UpdateProfileView(APIView):
    pass

class LoginView(APIView):
    def get(self,request):
        return render(request,'user/login.html')
    
    def post(self, request):
        username = request.data.get('username')
        password = request.data.get('password')
        if username == None:
            return render(request, 'user/failure.html')
        
        if  password == None:
            return render(request, 'user/failure.html')
            
        print("username :", username)
        print('password :',password)

        user = authenticate(username=username, password=password)
        print(user)
        if user is not None:
            print("User Authentication Success")
            token, created = Token.objects.get_or_create(user=user)
            if user.is_superuser:
                return redirect('admin_index')
            
            return render(request, 'user/index.html', {'user_id':user.id})
        
        else:
            messages.error(request, 'Something Went Wrong! Try Again')
            return redirect('login')
 

PracticalTask/user/templates/user/admin_index.html
<!DOCTYPE html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    
</head>
<body>
    <div class="container">
        <h1>Welcome to the Admin Dashboard</h1>

        <div class="options">
            <h2>What would you like to do?</h2>
            <div class="button-group">
                
                <a href="{% url 'list_user' %}" class="button">Users</a>
                <br><br>
              
                <a href="{% url 'product:list_product' %}" class="button">Products</a>
            </div>
        </div>
    </div>
</body>
</html>

PracticalTask/user/templates/user/create_user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create User</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    {% if messages %}
    <div class="message-container">
        {% for message in messages %}
            <div class="message-container {{ message.tags }}">
                <p>{{ message }}</p>
            </div>
        {% endfor %}
    </div>
    {% endif %}
    <div class="container">
        <h1>Create a New User</h1>
        
        <form action="{% url 'create_user' %}" method="POST">
            {% csrf_token %}
            <!-- Username -->
            <label for="username">Username:</label>
            <input type="text" name="username" id="username" placeholder="Enter Username" required>

            <br><br>
            <!-- Email -->
            <label for="email">Email:</label>
            <input type="email" name="email" id="email" placeholder="Enter Email" required>

            <!-- Password -->
            {% comment %} <label for="password">Password:</label> {% endcomment %}
            <input type="hidden" name="password" id="password" placeholder="Enter Password" value="default:123">

            <br><br>
            <!-- Gender -->
            <label for="gender">Gender:</label>
            <select name="gender" id="gender" required>
                <option value="" disabled selected>Select Gender</option>
                <option value="M">Male</option>
                <option value="F">Female</option>
                <option value="O">Other</option>
                <option value="N">Not Specified</option>
            </select>

            <br><br>
            <!-- Phone Number -->
            <label for="phone_number">Phone Number:</label>
            <input type="text" name="phone_number" id="phone_number" placeholder="Enter Phone Number">

            <br><br>
            <!-- Address -->
            <label for="address">Address:</label>
            <textarea name="address" id="address" placeholder="Enter Address"></textarea>

            <!-- Active Checkbox -->
            <input type="hidden" name="is_active" id="is_active" value="False">

            <br><br>
            <!-- Superuser Checkbox -->
            <label for="is_superuser">
                
                Is Superuser
                <input type="checkbox" name="is_superuser" id="is_superuser">
            </label>

            <br><br>
            <button type="submit">Create User</button>
        </form>

        <br><br>
        <a href="{% url 'list_user' %}" class="back-link">User List</a>
    </div>
</body>
</html>

PracticalTask/user/templates/user/email.html
<p>Hi {{ user.username }},</p>
<p>Thank you for registering! To activate your account, please click the link below:</p>
<a href="{{ activation_url }}">Activate your account</a>
<p>If you did not request an account, please ignore this email.</p>

PracticalTask/user/templates/user/failure.html
<html>
    <head>
        <meta charset='UTF-8' />
        <meta name='viewport' content='width=device-width, initial-scale-1.0' />
        <title>error</title>
    </head>
    <body>
        
        {% if messages %}
            <div class="message-container">
                {% for message in messages %}
                    <div class="message-container {{ message.tags }}">
                        <p>{{ message }}</p>
                    </div>
                {% endfor %}
            </div>
        {% endif %}
        <h1>Oops! something went wrong.</p>
            
    </body>
</html>

PracticalTask/user/templates/user/index.html
<!DOCTYPE html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    
</head>
<body>
    <div class="container">
        <h1>Welcome to the Dashboard</h1>

        <div class="options">
            <h2>What would you like to do?</h2>
            <div class="button-group">
                
                <a href="{% url 'update_user' user_id %}" class="button">Update Profile Info</a>
                <br><br>
              
                <a href="{% url 'product:list_product' %}" class="button">View Product</a>
            </div>
        </div>
    </div>
</body>
</html>

PracticalTask/user/templates/user/list_user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Product List</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    
</head>
<body>

    {% if messages %}
    <div class="message-container">
        {% for message in messages %}
            <div class="message-container {{ message.tags }}">
                <p>{{ message }}</p>
            </div>
        {% endfor %}
    </div>
    {% endif %}

    <div class="container">
    <h1>Product List</h1>

    <a href="{% url 'admin_index' %}" class="create-btn">Home Page</a>
    <a href="{% url 'create_user' %}" class="create-btn">Create New User</a>

    <table class="product-table">
        <thead>
            <tr>
                <th>UserName</th>
                <th>Email</th>
                <th>Gender</th>
                <th>Phone Number</th>
                <th>Address</th>
                <th>Is Superuser</th>
                <th>Is Active</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for user in users %}
                <tr>
                    <td>{{ user.username }}</td>
                    <td>{{ user.email }}</td>
                    <td>{{ user.gender }}</td>
                    <td>{{ user.phone_number }}</td>
                    <td>{{ user.address }}</td>
                    <td>{{ user.is_active }}</td>
                    <td>{{ user.is_superuser }}</td>
                    <td>
                        <a href="{% url 'update_user' user.id %}" class="edit-btn">Edit</a>

                        <form action="{% url 'delete_user' user.id %}" method="POST" style="display:inline;">
                            {% csrf_token %}
                            <button type="submit" class="delete-btn" onclick="return confirm('Are you sure you want to delete this user?')">Delete</button>
                        </form> 
                        
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
</body>
</html>

PracticalTask/user/templates/user/login.html
<!-- templates/registration/login.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    {% if messages %}
    <div class="message-container">
        {% for message in messages %}
            <div class="message-container {{ message.tags }}">
                <p>{{ message }}</p>
            </div>
        {% endfor %}
    </div>
    {% endif %}
    <div class="container">
        <h2>Login</h2>
        <form action="{% url 'verify_login' %}" method="POST">
            {% csrf_token %}
            <input type="text" name="username" placeholder="Username" required>
            <br><br>
            <input type="password" name="password" placeholder="Password" required>
            <br><br>
            <button type="submit">Login</button>
        </form>
    </div>

</body>
</html>

PracticalTask/user/templates/user/set_password.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>

<div class="container">

    <h2>Set Your Password</h2>

    <form method="POST">
        {% csrf_token %}

        <label for="password">Password:</label>
        <input type="password" name="password" id="password" required><br>
        <br><br>
        <label for="confirm_password">Confirm Password:</label>
        <input type="password" name="confirm_password" id="confirm_password" required><br>
        <br><br>
        <button type="submit">Set Password</button>
    </form>
</div>
</body>
</html>

PracticalTask/user/templates/user/success.html
<html>
    <head>
        <meta charset='UTF-8' />
        <meta name='viewport' content='width=device-width, initial-scale-1.0' />
        <title>success</title>
    </head>
    <body>

        {% if messages %}
        <div class="message-container">
            {% for message in messages %}
                <div class="message-container {{ message.tags }}">
                    <p>{{ message }}</p>
                </div>
            {% endfor %}
        </div>
        {% endif %}
        <h1>Thanks for using!</p>
    </body>
</html>

PracticalTask/user/templates/user/update_user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create User</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    {% if messages %}
    <div class="message-container">
        {% for message in messages %}
            <div class="message-container {{ message.tags }}">
                <p>{{ message }}</p>
            </div>
        {% endfor %}
    </div>
    {% endif %}
    <div class="container">
        <h1>Update User</h1>
        
        <form method="POST">
            {% csrf_token %}
            <label for="username">Username:</label>
            <input type="text" name="username" id="username" value={{user.username}} required>

            <br><br>
            <label for="email">Email:</label>
            <input type="email" name="email" id="email" value={{user.email}} required>

            <br><br>
            <label for="gender">Gender:</label>
            <select name="gender" id="gender" required>
                <option value="" disabled {% if not user.gender %}selected{% endif %}>Select Gender</option>
                <option value="M" {% if user.gender == 'M' %} selected {% endif %}>Male</option>
                <option value="F" {% if user.gender == 'F' %} selected {% endif %}>Female</option>
                <option value="O" {% if user.gender == 'O' %} selected {% endif %}>Other</option>
                <option value="N" {% if user.gender == 'N' %} selected {% endif %}>Not Specified</option>
            </select>

            <br><br>
            <label for="phone_number">Phone Number:</label>
            <input type="text" name="phone_number" id="phone_number" value={{user.phone_number}}>

            <br><br>
            <label for="address">Address:</label>
            <textarea name="address" id="address" value={{user.address}}></textarea>

            {% if login_user.is_superuser %}
                <br><br>
                <label for="is_active">
                    Is Active
                <input type="checkbox" name="is_active" id="is_active" {% if user.is_active %} checked {%endif%}>
                </label>
                
               
                <label for="is_superuser">
                    
                    Is Superuser
                    <input type="checkbox" name="is_superuser" id="is_superuser" {% if user.is_superuser %} checked {%endif%}>
                </label>
    
            {% endif %}
            
            <br><br>
            <button type="submit">Save User</button>
        </form>

    </div>
</body>
</html>